on:
  pull_request:
    branches: 
      - develop
    types: [closed]

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
        git --version
        git status
        git tag
        git describe
