name: Commit date to master
on:
  pull_request:
    branches: 
      - develop
    types: [closed]
jobs:
  date:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v2

      - name: save current date
        run: |
          # do some operation that changes a file in the git repo
          date > time.txt

      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "karthikaideepan88"
          git config user.email "knalasekaran.consultant@newscorp.com"

      - name: commit
        run: |
          # Stage the file, commit and push
          git init
          git remote update
          git fetch 
          git checkout rebase-test
          git rebase develop
          git push -f origin rebase-test
